apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: keda-demo
  name: processor
  annotations:
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"processor:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"processor\")].image"}]
spec:
  selector:
    matchLabels:
      app: processor
  replicas: 1
  template:
    metadata:
      labels:
        app: processor
    spec:
      containers:
      - name: processor
        image: image-registry.openshift-image-registry.svc:5000/keda-demo/processor:latest
        env:
        - name: AMQP_HOST
          value: artemis-default-0-svc
        - name: AMQP_PORT
          value: '5672'
        - name: REQUESTS_ADDRESS
          value: requests
        - name: RESPONSES_ADDRESS
          value: responses
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: processor
  namespace: keda-demo
spec:
  scaleTargetRef:
    name: processor
  minReplicaCount:  0                               # No replicas if queue length is zero
  maxReplicaCount:  10                              # At most 10 replicas
  fallback:
    failureThreshold: 3
    replicas: 5                                     # When failing to read metric, create 5 replicas
  triggers:
  - type: artemis-queue
    metadata:
      managementEndpoint: "artemis-wconsj-0-svc-rte-keda-demo.apps.cluster-vm2k6.vm2k6.sandbox2819.opentlc.com:80"
      queueName: "requests"
      brokerName: "amq-broker"
      brokerAddress: "requests"
      queueLength: '10'                             # Creates 1 replica for every 10 element
      activationQueueLength: '1'                    # Activates this trigger whenever this queue is not empty
      username: 'quarkus'
      password: 'quarkus'
