
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: processor-cl
  namespace: keda-demo
spec:
  jobTargetRef:
    parallelism: 1
    completions: 1
    activeDeadlineSeconds: 600
    backoffLimit: 6
    template:
      spec:
        containers:
        - name: processor-cl
          image: image-registry.openshift-image-registry.svc:5000/keda-demo/processor-cl:latest
          env:
          - name: AMQP_HOST
            value: artemis-default-0-svc
          - name: AMQP_PORT
            value: '5672'
          - name: REQUEST_ADDRESS
            value: requests-cl
          - name: RESPONSE_ADDRESS
            value: responses-cl
  minReplicaCount:  0
  maxReplicaCount:  100
  triggers:
  - type: artemis-queue
    metadata:
      managementEndpoint: "artemis-wconsj-0-svc-rte-keda-demo.apps.cluster-vm2k6.vm2k6.sandbox2819.opentlc.com:80"
      queueName: "requests-cl"
      brokerName: "amq-broker"
      brokerAddress: "requests-cl"
      queueLength: '1'
      activationQueueLength: '1'
      username: 'quarkus'
      password: 'quarkus'